# Generated by Django 4.1.4 on 2024-02-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_friends_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
