# Generated by Django 5.0.1 on 2024-02-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_relationship_receiver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
