# Generated by Django 5.0.1 on 2024-02-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_user_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
